[package]
name = 'eudexr'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'eudexr'

[dependencies]
extendr-api = '*'
textdistance = "1.1.1"  # Use the latest version available on crates.io
