# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rusttest_wrappers", use_symbols = TRUE, package_name = "rusttest")

#' @usage NULL
#' @useDynLib rusttest, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' @export
Hash <- new.env(parent = emptyenv())

Hash$new <- function(strings) .Call(wrap__Hash__new, strings)

#' @rdname Hash
#' @usage NULL
#' @export
`$.Hash` <- function (self, name) { func <- Hash[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Hash` <- `$.Hash`


# nolint end
