# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_eudexr_wrappers", use_symbols = TRUE, package_name = "eudexr")

#' @usage NULL
#' @useDynLib eudexr, .registration = TRUE
NULL

#' @export
Difference <- new.env(parent = emptyenv())

Difference$dist <- function() .Call(wrap__Difference__dist, self)

Difference$xor <- function() .Call(wrap__Difference__xor, self)

Difference$hamming <- function() .Call(wrap__Difference__hamming, self)

Difference$similar <- function() .Call(wrap__Difference__similar, self)

#' @rdname Difference
#' @usage NULL
#' @export
`$.Difference` <- function (self, name) { func <- Difference[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Difference` <- `$.Difference`


# nolint end
